#cloud-config

# User Settings
#Use package 'mkpasswd' elsewhere to create hashed passwords. Don't paste cleartext here!
disable_root: false
users:
  - name: root
    hashed_passwd: '$6$o0Y/KFOCnW.4/6Vo$49FCjpmwcq9m08UK0WIDI70lCd4m8B/0eEvJqvvt8l4MWL581QsDBtdnD1da8yO5lNk6Kk1v/EmPW3UMzMkpd0'
    lock_passwd: false
    shell: /bin/bash
  - name: deiberts86
    hashed_passwd: '$6$o0Y/KFOCnW.4/6Vo$49FCjpmwcq9m08UK0WIDI70lCd4m8B/0eEvJqvvt8l4MWL581QsDBtdnD1da8yO5lNk6Kk1v/EmPW3UMzMkpd0'
    homedir: /home/deiberts86
    lock_passwd: false
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - >
      ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAABgQC7AU9EHNkkqw6AY1emSjfk6Wv9AbrG594U8INnueKNNYTCYXqBCRdcOf0g2Hj8z6uDqvR21Ps0nWbctLUZXPhAWbw2SWcfNE9wH3mH3lpP+xZ6iqM8iz6NxalTmed0TXC76SaGrRmi97KIRa6UcwdzsPmvf2OuNZWvnTJqeAzpk3j78KhofA5wOIFbWkmmxG30fXybwzJUAnheKMW7JE89UKqLZZP+M5AhQwNJZi/dv1W12hm4BVoBcBtdsHvC2oTQRxLVqFBprGYTV4TeW8dlbWNi0OKmFkDXaEHd0aQReVWyu21WvArshQNwDjwt3hXBQevRcc12gsnInE0LHNPKM7x/8vlULnq1UFjDfBBJHyH0NtxIgTLb2Wf1/qCINi3rTudigQn0KnpPUry1C01s+V0JVZ09/KgQFz8Cu+HsX8Fuz+lYf0jfK6C40ehhmrfkggZnKS8ePK9wgpdC7VnF6qMbvQc0zXWnVHLrYAPKNtbhVgespUYh0mTd8S9Kf3s= shaundeibert@SD-J9WL2DD6NY
    - >
      ssh-rsa
      AAAAB3NzaC1yc2EAAAADAQABAAABgQDGU6Ig2WfvKsipXpEQJ3Aewh8RYLTikSo6UZ3F9ZctQ1OpEf8pXWnkYKX6l3nNqXfGPFeerhugLvbGA+P0Jks/KkgXQEGrtJncZxCYlVEEDdHNIJfPaLtgg5z3vHGqyi6t+2wqGzLN+rr6gCUVJsWkEVrlhujkN4pDorekXWi1LeAV05+I9bdzetlzIo9aAsNrHfItnebf954O/bgXVuwzLX+VUpEABj+yauvR6tk+fvriaS+gE3C8eSckRWrAwIYZ+1n6amT8ai0fWEEZ68bKepZKFtk/FIi9HbTrYca964azhlDMoUQvaH2KSL2QVEUIw7e3yv7tVBLIsed6mRGCeKJ/CBnSXUDv0z6YXCyNNGsyKqcfDk0R9z0nBXELFk12EQ8Fz05+ji9JevheoEUGpP6X1FIcX3nN3E1QKrpvUWo/McxSE+W6x3mHMjdIg4bPULfU8DQirNwb3cTR+6juYtBfuxhh1fxatGXEI//p4L4DQyY4+x4pMZ5/vG2w4h0= tetra@Hopeless-2023

# Packages

package_update: true

packages:
  - vim
  - sudo
  - net-tools
  - dnsutils
  - nfs-common
  - open-iscsi
  - iptables
  - qemu-guest-agent
  - auditd

# Files to create for Linux Host

write_files:
  - path: /etc/sysctl.d/60-rke2.conf
    content: |
        # Kernel Tuning for RKE2
        vm.swappiness=0
        vm.panic_on_oom=0
        vm.overcommit_memory=1
        kernel.panic=10
        kernel.panic_on_oops=1
        vm.max_map_count = 262144
        net.ipv4.ip_local_port_range=1024 65000
        Increase max connection
        net.core.somaxconn=10000
        net.ipv4.tcp_tw_reuse=1
        net.ipv4.tcp_fin_timeout=15
        net.core.somaxconn=4096
        net.core.netdev_max_backlog=4096
        net.core.rmem_max=16777216
        net.core.wmem_max=16777216
        net.ipv4.tcp_max_syn_backlog=20480
        net.ipv4.tcp_max_tw_buckets=400000
        net.ipv4.tcp_no_metrics_save=1
        net.ipv4.tcp_rmem=4096 87380 16777216
        net.ipv4.tcp_syn_retries=2
        net.ipv4.tcp_synack_retries=2
        net.ipv4.tcp_wmem=4096 65536 16777216
        net.ipv4.tcp_keepalive_time=600
        net.ipv4.ip_forward=1
        net.ipv6.ip_forward=1
        fs.inotify.max_user_instances=8192
        fs.inotify.max_user_watches=1048576
  - path: /etc/issue
    content: |
      **********************************************************

      Ubuntu 22.04.3 LTS \n \l

      This is a cloud-init image that has logical volumes for
      both the /var/lib/rancher and /var/lib/longhorn
      directories. This is to prep for RKE2 or K3S installation.
      If this is not the desired outcome, please adjust the
      runcmd fields as needed.

      **********************************************************

# Execute 'runcmd' with sleep commands sprinkled in as some processes need to happen in order before completion

runcmd:
- mkdir -p /etc/rancher/rke2
- mkdir -p /var/lib/rancher
- mkdir -p /var/lib/longhorn
- sgdisk -n 1:2048:+99G -t 1:8e00 /dev/vdc -p
- sgdisk -n 1:2048:+299G -t 1:8e00 /dev/vdd -p
- sleep 5
- pvcreate /dev/vdc1
- pvcreate /dev/vdd1
- sleep 5
- vgcreate rancher /dev/vdc1
- vgcreate longhorn /dev/vdd1
- sleep 5
- lvcreate -l 100%FREE rancher /dev/vdc1
- lvcreate -l 100%FREE longhorn /dev/vdd1
- sleep 5
- mkfs.ext4 /dev/rancher/lvol0
- mkfs.ext4 /dev/longhorn/lvol0
- sleep 5
- echo 'dev/rancher/lvol0  /var/lib/rancher  ext4  defaults  0  0' | tee -a /etc/fstab
- echo 'dev/longhorn/lvol0  /var/lib/longhorn  ext4  defaults  0  0' | tee -a /etc/fstab
- systemctl enable --now iscsid
- timedatectl set-timezone "America/New_York"
- systemctl enable --now qemu-guest-agent
- useradd -r -c "etcd user" -s /sbin/nologin -M etcd -U
# disable cloud-init after completion
- touch /etc/cloud/cloud-init.disabled
# reboot system for /etc/fstab to take hold (autoMount) new disks
- mount /dev/rancher/lvol0 /var/lib/rancher
- mount /dev/longhorn/lvol0 /var/lib/longhorn